### ISSUE TITLE
Failed to list/discover a local hostname

### ISSUE THREAD

**Issue by c9s** [pyrus/Pyrus#89]
Hi,

I have my own hostname defined in /etc/hosts, called pear_local, and is mapping to 127.0.0.1

But I can't discover this channel through PEAR neither Pyrus: 

```
$ pyrus.phar channel-discover pear_local

Pyrus version 2.0.0a3 SHA-1: BE7EA9D171AE3873F1BBAF692EEE9165BB14BD5D
Using PEAR installation found at /Users/c9s/local
Discovery of channel pear_local successful
```

And failed when listing channels:

```
$ sudo pyrus.phar list-channels 

Pyrus version 2.0.0a3 SHA-1: BE7EA9D171AE3873F1BBAF692EEE9165BB14BD5D
Using PEAR installation found at /Users/c9s/local
Unable to add all custom roles/tasks/commands: exception 'PEAR2\Pyrus\Channel\Exception' with message 'Primary server "pear_local" is not a valid channel server' in phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ChannelFile/v1.php:301
Stack trace:
#0 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ChannelFile/v1.php(269): PEAR2\Pyrus\ChannelFile\v1->setName('pear_local')
#1 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ChannelRegistry/Sqlite3.php(312): PEAR2\Pyrus\ChannelFile\v1->__set('name', 'pear_local')
#2 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ChannelRegistry/Sqlite3.php(265): PEAR2\Pyrus\ChannelRegistry\Sqlite3->getChannelObject('pear_local')
#3 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ChannelRegistry/Base.php(240): PEAR2\Pyrus\ChannelRegistry\Sqlite3->get('pear_local')
#4 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/PluginRegistry.php(71): PEAR2\Pyrus\ChannelRegistry\Base->current()
#5 phar:///Users/c9s/bin/pyrus.phar/PEAR2_Pyrus-2.0.0a3/php/PEAR2/Pyrus/ScriptFrontend/Commands.php(260): PEAR2\Pyrus\PluginRegistry->scan()
#6 /Users/c9s/bin/pyrus.phar(51): PEAR2\Pyrus\ScriptFrontend\Commands->run(Array)
#7 {main}
Listing channels [/Users/c9s/local]:
PEAR2\Pyrus\Channel\Exception: Primary server "pear_local" is not a valid channel server
```

**Comment by saltybeagle** [comment]
Could you supply your channel.xml?

**Comment by fpoirotte** [comment]
The underscore character (_) is not valid in hostnames and the regexp at https://github.com/pyrus/Pyrus/blob/master/src/Pyrus/ChannelFile/v1.php#L313 rejects it.
Anyway, accepting it may be a good idea because some operating systems (eg. Windows) allow it in various identifiers (eg. computer names in a network group).

**Comment by c9s** [comment]
Hi,

which doesn't show a proper error message, yes it will be nice if pyrus can accepting underscore. :-)

I've fixed this problem, actually I was working on this pear mirror tool: MiniPear https://github.com/c9s/MiniPear

**Comment by cweiske** [comment]
How did you fix this problem?

**Comment by c9s** [comment]
well,  not to use underscore, use dash instead of it.

**Comment by fpoirotte** [comment]
IHMO, we should either accept underscores or reject them during the call to channel-discover.
I have a patch ready for both of these solutions.

**Comment by cweiske** [comment]
According to RFC 2396 (URLs), section "3.2.2. Server-based Naming Authority", underscores are not allowed:

```
      host          = hostname | IPv4address
      hostname      = *( domainlabel "." ) toplabel [ "." ]
      domainlabel   = alphanum | alphanum *( alphanum | "-" ) alphanum
      toplabel      = alpha | alpha *( alphanum | "-" ) alphanum
```

We should thus not accept underscores but reject them.

**Comment by c9s** [comment]
Should prompt readable error message for this kind of validation. :-)
